name: Build, Push and Update Compose

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 3. Set Docker image tag
        id: vars
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: 4. Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/course_platform_server
          SHA=${{ steps.vars.outputs.sha_short }}

          docker build -t $IMAGE:latest -t $IMAGE:$SHA ./server

      - name: 5. Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/course_platform_server
          SHA=${{ steps.vars.outputs.sha_short }}

          docker push $IMAGE:latest
          docker push $IMAGE:$SHA
